#ifndef GENRE_H
#define GENRE_H

#include <QHash>
#include <QString>

class Genre {
public:
    ~Genre() {
        delete genres;
        delete vkGenres;
        delete equalities;
    }

    static Genre * instance();

    static void close() {
        delete self;
    }

    int toInt(QString name) const;

private:
    Genre() {
        vkGenres = new QHash<int, QString>();

        vkGenres -> insert(1, QString("Rock"));
        vkGenres -> insert(2, QString("Pop"));
        vkGenres -> insert(3, QString("Rap & Hip-Hop"));
        vkGenres -> insert(4, QString("Easy Listening"));
        vkGenres -> insert(5, QString("Dance & House"));
        vkGenres -> insert(6, QString("Instrumental"));
        vkGenres -> insert(7, QString("Metal"));
        vkGenres -> insert(8, QString("Dubstep"));
        vkGenres -> insert(9, QString("Jazz & Blues"));
        vkGenres -> insert(10, QString("Drum & Bass"));
        vkGenres -> insert(11, QString("Trance"));
        vkGenres -> insert(12, QString("Chanson"));
        vkGenres -> insert(13, QString("Ethnic"));
        vkGenres -> insert(14, QString("Acoustic & Vocal"));
        vkGenres -> insert(15, QString("Reggae"));
        vkGenres -> insert(16, QString("Classical"));
        vkGenres -> insert(17, QString("Indie Pop"));
        vkGenres -> insert(18, QString("Other"));
        vkGenres -> insert(19, QString("Speech"));
        vkGenres -> insert(21, QString("Alternative"));
        vkGenres -> insert(22, QString("Electropop & Disco"));


        genres = new QHash<int, QString>();

        genres -> insert(0,   "Blues");
        genres -> insert(1,   "Classic Rock");
        genres -> insert(2,   "Country");
        genres -> insert(3,   "Dance");
        genres -> insert(4,   "Disco");
        genres -> insert(5,   "Funk");
        genres -> insert(6,   "Grunge");
        genres -> insertMulti(7,   "Hip-Hop");
        genres -> insertMulti(7,   "HipHop");

        genres -> insert(8,   "Jazz");
        genres -> insert(9,   "Metal");
        genres -> insert(10,  "New Age");
        genres -> insert(11,  "Oldies");
        genres -> insert(12,  "Other");
        genres -> insert(13,  "Pop");
        genres -> insert(14,  "Rhythm and Blues");
        genres -> insert(15,  "Rap");
        genres -> insert(16,  "Reggae");
        genres -> insert(17,  "Rock");
        genres -> insert(18,  "Techno");
        genres -> insert(19,  "Industrial");
        genres -> insert(20,  "Alternative");
        genres -> insert(21,  "Ska");
        genres -> insert(22,  "Death Metal");
        genres -> insert(23,  "Pranks");
        genres -> insert(24,  "Soundtrack");
        genres -> insert(25,  "Euro-Techno");
        genres -> insert(26,  "Ambient");
        genres -> insertMulti(27,  "Trip-Hop");
        genres -> insertMulti(27,  "TripHop");
        genres -> insert(28,  "Vocal");
        genres -> insert(29,  "Jazz & Funk");
        genres -> insert(30,  "Fusion");
        genres -> insert(31,  "Trance");
        genres -> insert(32,  "Classical");
        genres -> insert(33,  "Instrumental");
        genres -> insert(34,  "Acid");
        genres -> insert(35,  "House");
        genres -> insert(36,  "Game");
        genres -> insert(37,  "Sound Clip");
        genres -> insert(38,  "Gospel");
        genres -> insert(39,  "Noise");
        genres -> insert(40,  "Alternative Rock");
        genres -> insert(41,  "Bass");
        genres -> insert(42,  "Soul");
        genres -> insert(43,  "Punk");
        genres -> insert(44,  "Space");
        genres -> insert(45,  "Meditative");
        genres -> insert(46,  "Instrumental Pop");
        genres -> insert(47,  "Instrumental Rock");
        genres -> insert(48,  "Ethnic");
        genres -> insert(49,  "Gothic");
        genres -> insert(50,  "Darkwave");
        genres -> insert(51,  "Techno-Industrial");
        genres -> insert(52,  "Electronic");
        genres -> insert(53,  "Pop-Folk");
        genres -> insert(54,  "Eurodance");
        genres -> insert(55,  "Dream");
        genres -> insert(56,  "Southern Rock");
        genres -> insert(57,  "Comedy");
        genres -> insert(58,  "Cult");
        genres -> insert(59,  "Gangsta");
        genres -> insert(60,  "Top 40");
        genres -> insert(61,  "Christian Rap");
        genres -> insert(62,  "Pop/Funk");
        genres -> insert(63,  "Jungle");
        genres -> insert(64,  "Native American");
        genres -> insert(65,  "Cabaret");
        genres -> insert(66,  "New Wave");
        genres -> insert(67,  "Psychedelic");
        genres -> insert(68,  "Rave");
        genres -> insert(69,  "Showtunes");
        genres -> insert(70,  "Trailer");
        genres -> insert(71,  "Lo-Fi");
        genres -> insert(72,  "Tribal");
        genres -> insert(73,  "Acid Punk");
        genres -> insert(74,  "Acid Jazz");
        genres -> insert(75,  "Polka");
        genres -> insert(76,  "Retro");
        genres -> insert(77,  "Musical");
        genres -> insert(78,  "Rock & Roll");
        genres -> insert(79,  "Hard Rock");
        genres -> insert(80,  "Folk");
        genres -> insert(81,  "Folk-Rock");
        genres -> insert(82,  "National Folk");
        genres -> insert(83,  "Swing");
        genres -> insert(84,  "Fast Fusion");
        genres -> insert(85,  "Bebop");
        genres -> insert(86,  "Latin");
        genres -> insert(87,  "Revival");
        genres -> insert(88,  "Celtic");
        genres -> insert(89,  "Bluegrass");
        genres -> insert(90,  "Avantgarde");
        genres -> insert(91,  "Gothic Rock");
        genres -> insert(92,  "Progressive Rock");
        genres -> insert(93,  "Psychedelic Rock");
        genres -> insert(94,  "Symphonic Rock");
        genres -> insert(95,  "Slow Rock");
        genres -> insert(96,  "Big Band");
        genres -> insert(97,  "Chorus");
        genres -> insert(98,  "Easy Listening");
        genres -> insert(99,  "Acoustic");
        genres -> insert(100, "Humour");
        genres -> insert(101, "Speech");
        genres -> insert(102, "Chanson");
        genres -> insert(103, "Opera");
        genres -> insert(104, "Chamber Music");
        genres -> insert(105, "Sonata");
        genres -> insert(106, "Symphony");
        genres -> insert(107, "Booty Bass");
        genres -> insert(108, "Primus");
        genres -> insert(109, "Porn groove");
        genres -> insert(110, "Satire");
        genres -> insert(111, "Slow Jam");
        genres -> insert(112, "Club");
        genres -> insert(113, "Tango");
        genres -> insert(114, "Samba");
        genres -> insert(115, "Folklore");
        genres -> insert(116, "Ballad");
        genres -> insert(117, "Power Ballad");
        genres -> insert(118, "Rhythmic Soul");
        genres -> insert(119, "Freestyle");
        genres -> insert(120, "Duet");
        genres -> insert(121, "Punk Rock");
        genres -> insert(122, "Drum Solo");
        genres -> insert(123, "A capella");
        genres -> insert(124, "Euro-House");
        genres -> insert(125, "Dance Hall");
        genres -> insert(126, "Goa");
        genres -> insert(127, "Drum & Bass");
        genres -> insert(128, "Club-House");
        genres -> insert(129, "Hardcore Techno");
        genres -> insert(130, "Terror");
        genres -> insert(131, "Indie");
        genres -> insert(132, "BritPop");
        genres -> insert(133, "Afro-punk");
        genres -> insert(134, "Polsk Punk");
        genres -> insert(135, "Beat");
        genres -> insert(136, "Christian Gangsta Rap");
        genres -> insert(137, "Heavy Metal");
        genres -> insert(138, "Black Metal");
        genres -> insert(139, "Crossover");
        genres -> insert(140, "Contemporary Christian");
        genres -> insert(141, "Christian Rock");
        genres -> insert(142, "Merengue");
        genres -> insert(143, "Salsa");
        genres -> insert(144, "Thrash Metal");
        genres -> insert(145, "Anime");
        genres -> insert(146, "Jpop");
        genres -> insert(147, "Synthpop");
        genres -> insert(148, "Abstract");
        genres -> insert(149, "Art Rock");
        genres -> insert(150, "Baroque");
        genres -> insert(151, "Bhangra");
        genres -> insert(152, "Big Beat");
        genres -> insert(153, "Breakbeat");
        genres -> insert(154, "Chillout");
        genres -> insert(155, "Downtempo");
        genres -> insert(156, "Dub");
        genres -> insert(157, "EBM");
        genres -> insert(158, "Eclectic");
        genres -> insert(159, "Electro");
        genres -> insert(160, "Electroclash");
        genres -> insert(161, "Emo");
        genres -> insert(162, "Experimental");
        genres -> insert(163, "Garage");
        genres -> insert(164, "Global");
        genres -> insert(165, "IDM");
        genres -> insert(166, "Illbient");
        genres -> insert(167, "Industro-Goth");
        genres -> insert(168, "Jam Band");
        genres -> insert(169, "Krautrock");
        genres -> insert(170, "Leftfield");
        genres -> insert(171, "Lounge");
        genres -> insert(172, "Math Rock");
        genres -> insert(173, "New Romantic");
        genres -> insert(174, "Nu-Breakz");
        genres -> insert(175, "Post-Punk");
        genres -> insert(176, "Post-Rock");
        genres -> insert(177, "Psytrance");
        genres -> insert(178, "Shoegaze");
        genres -> insert(179, "Space Rock");
        genres -> insert(180, "Trop Rock");
        genres -> insert(181, "World Music");
        genres -> insert(182, "Neoclassical");
        genres -> insert(183, "Audiobook");
        genres -> insert(184, "Audio Theatre");
        genres -> insert(185, "Neue Deutsche Welle");
        genres -> insert(186, "Podcast");
        genres -> insert(187, "Indie Rock");
        genres -> insert(188, "G-Funk");
        genres -> insert(189, "Dubstep");
        genres -> insert(190, "Garage Rock");
        genres -> insert(191, "Psybient");

        equalities = new QHash<int, int>();

//        equalities -> insert(0, );
//        equalities -> insert(1, );
//        equalities -> insert(2, );
//        equalities -> insert(3, );
//        equalities -> insert(4, );
//        equalities -> insert(5, );
//        equalities -> insert(6, );
//        equalities -> insert(7, );
//        equalities -> insert(8, );
//        equalities -> insert(9, );
//        equalities -> insert(10, );
//        equalities -> insert(11, );
//        equalities -> insert(12, );
//        equalities -> insert(13, );
//        equalities -> insert(14, );
//        equalities -> insert(15, );
//        equalities -> insert(16, );
//        equalities -> insert(17, );
//        equalities -> insert(18, );
//        equalities -> insert(19, );
//        equalities -> insert(20, );
//        equalities -> insert(21, );
//        equalities -> insert(22, );
//        equalities -> insert(23, );
//        equalities -> insert(24, );
//        equalities -> insert(25, );
//        equalities -> insert(26, );
//        equalities -> insert(27, );
//        equalities -> insert(28, );
//        equalities -> insert(29, );
//        equalities -> insert(30, );
//        equalities -> insert(31, );
//        equalities -> insert(32, );
//        equalities -> insert(33, );
//        equalities -> insert(34, );
//        equalities -> insert(35, );
//        equalities -> insert(36, );
//        equalities -> insert(37, );
//        equalities -> insert(38, );
//        equalities -> insert(39, );
//        equalities -> insert(40, );
//        equalities -> insert(41, );
//        equalities -> insert(42, );
//        equalities -> insert(43, );
//        equalities -> insert(44, );
//        equalities -> insert(45, );
//        equalities -> insert(46, );
//        equalities -> insert(47, );
//        equalities -> insert(48, );
//        equalities -> insert(49, );
//        equalities -> insert(50, );
//        equalities -> insert(51, );
//        equalities -> insert(52, );
//        equalities -> insert(53, );
//        equalities -> insert(54, );
//        equalities -> insert(55, );
//        equalities -> insert(56, );
//        equalities -> insert(57, );
//        equalities -> insert(58, );
//        equalities -> insert(59, );
//        equalities -> insert(60, );
//        equalities -> insert(61, );
//        equalities -> insert(62, );
//        equalities -> insert(63, );
//        equalities -> insert(64, );
//        equalities -> insert(65, );
//        equalities -> insert(66, );
//        equalities -> insert(67, );
//        equalities -> insert(68, );
//        equalities -> insert(69, );
//        equalities -> insert(70, );
//        equalities -> insert(71, );
//        equalities -> insert(72, );
//        equalities -> insert(73, );
//        equalities -> insert(74, );
//        equalities -> insert(75, );
//        equalities -> insert(76, );
//        equalities -> insert(77, );
//        equalities -> insert(78, );
//        equalities -> insert(79, );
//        equalities -> insert(80, );
//        equalities -> insert(81, );
//        equalities -> insert(82, );
//        equalities -> insert(83, );
//        equalities -> insert(84, );
//        equalities -> insert(85, );
//        equalities -> insert(86, );
//        equalities -> insert(87, );
//        equalities -> insert(88, );
//        equalities -> insert(89, );
//        equalities -> insert(90, );
//        equalities -> insert(91, );
//        equalities -> insert(92, );
//        equalities -> insert(93, );
//        equalities -> insert(94, );
//        equalities -> insert(95, );
//        equalities -> insert(96, );
//        equalities -> insert(97, );
//        equalities -> insert(98, );
//        equalities -> insert(99, );
//        equalities -> insert(100, );
//        equalities -> insert(101, );
//        equalities -> insert(102, );
//        equalities -> insert(103, );
//        equalities -> insert(104, );
//        equalities -> insert(105, );
//        equalities -> insert(106, );
//        equalities -> insert(107, );
//        equalities -> insert(108, );
//        equalities -> insert(109, );
//        equalities -> insert(110, );
//        equalities -> insert(111, );
//        equalities -> insert(112, );
//        equalities -> insert(113, );
//        equalities -> insert(114, );
//        equalities -> insert(115, );
//        equalities -> insert(116, );
//        equalities -> insert(117, );
//        equalities -> insert(118, );
//        equalities -> insert(119, );
//        equalities -> insert(120, );
//        equalities -> insert(121, );
//        equalities -> insert(122, );
//        equalities -> insert(123, );
//        equalities -> insert(124, );
//        equalities -> insert(125, );
//        equalities -> insert(126, );
//        equalities -> insert(127, );
//        equalities -> insert(128, );
//        equalities -> insert(129, );
//        equalities -> insert(130, );
//        equalities -> insert(131, );
//        equalities -> insert(132, );
//        equalities -> insert(133, );
//        equalities -> insert(134, );
//        equalities -> insert(135, );
//        equalities -> insert(136, );
//        equalities -> insert(137, );
//        equalities -> insert(138, );
//        equalities -> insert(139, );
//        equalities -> insert(140, );
//        equalities -> insert(141, );
//        equalities -> insert(142, );
//        equalities -> insert(143, );
//        equalities -> insert(144, );
//        equalities -> insert(145, );
//        equalities -> insert(146, );
//        equalities -> insert(147, );
//        equalities -> insert(148, );
//        equalities -> insert(149, );
//        equalities -> insert(150, );
//        equalities -> insert(151, );
//        equalities -> insert(152, );
//        equalities -> insert(153, );
//        equalities -> insert(154, );
//        equalities -> insert(155, );
//        equalities -> insert(156, );
//        equalities -> insert(157, );
//        equalities -> insert(158, );
//        equalities -> insert(159, );
//        equalities -> insert(160, );
//        equalities -> insert(161, );
//        equalities -> insert(162, );
//        equalities -> insert(163, );
//        equalities -> insert(164, );
//        equalities -> insert(165, );
//        equalities -> insert(166, );
//        equalities -> insert(167, );
//        equalities -> insert(168, );
//        equalities -> insert(169, );
//        equalities -> insert(170, );
//        equalities -> insert(171, );
//        equalities -> insert(172, );
//        equalities -> insert(173, );
//        equalities -> insert(174, );
//        equalities -> insert(175, );
//        equalities -> insert(176, );
//        equalities -> insert(177, );
//        equalities -> insert(178, );
//        equalities -> insert(179, );
//        equalities -> insert(180, );
//        equalities -> insert(181, );
//        equalities -> insert(182, );
//        equalities -> insert(183, );
//        equalities -> insert(184, );
//        equalities -> insert(185, );
//        equalities -> insert(186, );
//        equalities -> insert(187, );
//        equalities -> insert(188, );
//        equalities -> insert(189, );
//        equalities -> insert(190, );
//        equalities -> insert(191, );
    }

    static Genre *self;

    QHash<int, QString> * genres;
    QHash<int, QString> * vkGenres;
    QHash<int, int> * equalities;
};

#endif // GENRE_H
